// let name = prompt ('Put your name')
// alert('hello ' + name + '!')
// let age = prompt ('what is your age?')
// alert ( name + ' is ' + age)
// let more = prompt ('сколько тебе лет?')
// alert (name + ' тебе ' + age + ' лет ')

const name = prompt (' Your name: ')
const surname = prompt (' Your lastname: ')
let age = prompt (' Your age: ')
let education = prompt (' Your education: ')
let sex = prompt (' sex: ')
let height = prompt (' Your height: ')
let hobby = prompt (' Your hobby: ')
alert(name + " " + surname + ' is ' + age + ' she has ' + education + ' education ' + ' she is ' + sex + ' her heigh is ' + height + " " + 'and' + " " + 'she loves ' +  hobby)